biolab_simulator/biolab_simulator/urls.py
import imp
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('density/', include('density.urls')),
    path('cetane-number/', include('cetaneNumber.urls')),
    path('plugging-point/', include('pluggingPoint.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biolab_simulator/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('home.urls')),
    path('density/', include('density.urls')),
    path('cetane-number/', include('cetaneNumber.urls')),
    path('plugging-point/', include('pluggingPoint.urls')),
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

cetaneNumber/urls.py
from django.urls import path
from . import views

app_name = 'cetaneNumber'

urlpatterns = [
    path('', views.CetaneNumber.as_view(), name='cetaneNumber'),
    path('Lapuerta-Rodriguez-Mora/', views.LapuertaRodriguez.as_view(), name='lapuerta_rodriguez'),
    path('Lapuerta-Rodriguez-Mora-only-FAME/', views.LapuertaRodriguezSimplified.as_view(), name='lapuerta_rodriguez_simplified'),
]

density/urls.py
from django.urls import path
from .models import *
from . import views

app_name = 'density'

urlpatterns = [
    path('', views.Density.as_view(), name='density'),
    path('Murnaghan-Equation/', views.MurnaghanEquation.as_view(), name='murnaghan_equation'),
    path('Chhetri-Watts/', views.ChhetriWatts.as_view(), name='chhetri_watts'),
    path('Rackett-Soave/', views.RackettSoave.as_view(), name='rackett_soave'),
    path('Estrutura-molecular/', views.MolecularStructure.as_view(), name='molecular_structure'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('contact/', views.contact, name='contact')
]

pluggingPoint/urls.py
from django.urls import path
from . import views

app_name = 'pluggingPoint'

urlpatterns = [
    path('', views.PluggingPoint.as_view(), name='pluggingPoint'),
    # path('Li-Bing-et-al./', views.LiBing.as_view(), name="li_bing"),
]

biolab_simulator/templates/partial/_navbar.html
{% load static %}

<input id="close-menu" class="close-menu" type="checkbox"  aria-label="Close menu" role="button">
<label class="close-menu-label invisible-item" for="close-menu" title="close menu">≡</label>
<nav>
    <div class="logo"><a href="{% url 'home:home' %}" onclick="getElementById('close-menu')">BLSIM</a></div>
    <ul>
        <li class="option"><a href="{% url 'home:home' %}">Home</a></li>
        <li class="option">
            <a href="{% url 'density:density' %}">Massa específica <i class="arrow down"></i></a>
            <ul>
                <li><a href="{% url 'density:murnaghan_equation' %}">Murnaghan</a></li>
                <li><a href="{% url 'density:chhetri_watts' %}">Regressão</a></li>
                <li><a href="{% url 'density:rackett_soave' %}">Rackett-Soave</a></li>
                <li><a href="{% url 'density:molecular_structure' %}">Estrutura molecular</a></li>
            </ul>
        </li>
        <li class="option">
            <a href="{% url 'cetaneNumber:cetaneNumber' %}">Número de cetano <i class="arrow down"></i></a>
            <ul>
                <li><a href="{% url 'cetaneNumber:lapuerta_rodriguez_simplified' %}">FAMEs</a></li>
                <li><a href="{% url 'cetaneNumber:lapuerta_rodriguez' %}">FAMEs e outros</a></li>
            </ul>
        </li>
        <li class="option"><a href="{% url 'pluggingPoint:pluggingPoint' %}">CFPP</a></li>
        <li class="option"><a href="{% url 'home:contact' %}">Contact</a></li>
    </ul>
</nav>